### ISSUE TITLE
sklearn version issue between model and spectracl

### ISSUE THREAD

**Issue by bryan-brancotte** [scwatts/spectracl#7]
Hi, 

I am getting an error, but not for all test data. Following the error attached I guess it is because the model have been generated with sklean `0.23.2`, but spectracl does not indicate that it want `0.23.*` and my install ends up with `1.0.2`.

Could you either generate the model with a more recent version of sklearn? Documentation [recommends using 1.0](https://scikit-learn.org/0.23/). If not possible could you specify that the requirements should be 0.23.2 in requirements.txt ?
```txt
pandas
numpy
scipy
sklearn~=0.23.2
```

### Error log

```log
Failed to run command: spectracl (...)
stdout: 
stderr: /usr/local/lib/python3.10/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.23.2 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/usr/local/lib/python3.10/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.23.2 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
Traceback (most recent call last):
  File "/usr/local/bin/spectracl", line 8, in <module>
    sys.exit(entry())
  File "/usr/local/lib/python3.10/site-packages/spectracl/__main__.py", line 37, in entry
    for sp in (spectra.Spectra(fid_fp) for fid_fp in fid_fps):
  File "/usr/local/lib/python3.10/site-packages/spectracl/__main__.py", line 37, in <genexpr>
    for sp in (spectra.Spectra(fid_fp) for fid_fp in fid_fps):
  File "/usr/local/lib/python3.10/site-packages/spectracl/spectra.py", line 20, in __init__
    self.acqu_data = read_acqu_data(self.acqu_fp)
  File "/usr/local/lib/python3.10/site-packages/spectracl/spectra.py", line 88, in read_acqu_data
    assert all(d['name'] in acqu_data for d in acqu_fields.values())
AssertionError
```

**Comment by scwatts** [comment]
I'll enforce `sklearn~=0.23.2` for now until I have more time to work on this project. Thanks for opening the issue.

**Comment by bryan-brancotte** [comment]
Hi @scwatts

FYI: when switching to sklean 0.23.2 I wasn't able to install numpy anymore on [python 3.10](https://gitlab.pasteur.fr/hub/ktyper/-/jobs/194457). I had to switch to python 3.9.
